name: HeartManager
version: 10.0
main: com.gmail.bobason01.HeartManager
api-version: 1.20
depend: [ProtocolLib]
author: crston
commands:
  heartmanager:
    description: HeartManager Main Command
    aliases: [hm]
permissions:
  heartmanager.admin:
    description: HeartManager Admin Permission
    default: op